version: '3.4'
services:
  server:
    image: servergit:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/githelper/:/home/repos/
  client:
    image: clientgit:latest
    restart: always
    ports:
      - 3030:3030

