appport = "8080"
datadir = "data/"
clientId = "clientId"
clientSecret = "clientSecret"
authUrl = "https://github.com/login/oauth/authorize"
tokenUrl = "https://github.com/login/oauth/access_token"
clientRedirectUrl = "http://localhost:3030/#/repos"